### ISSUE TITLE
Don't crash when `commit.gpgsign` is enabled

### ISSUE THREAD

**Issue by blinry** [git-learning-game/git-hydra#3]
As mentioned in #2 by @tasmo, this currently can be a problem – I'm guessing because the gpg would require the user to interactively enter their password. We should override the setting in the game environment.

**Comment by blinry** [comment]
@tasmo, you're very welcome to try again and check where the game breaks now! :D

**Comment by marzipankaiser** [comment]
This still is a problem for me.

# System details
- `uname -a` -> `Linux gaisseml-nixos 5.10.14 #1-NixOS SMP Sun Feb 7 14:37:17 UTC 2021 x86_64 GNU/Linux`
- running game using `steam-run`
- Git config file (... means values left out, from `~/.config/git/config`):
```
[commit]
	gpgSign = true

[github]
	user = "marzipankaiser"

[gpg]
	program = "..."

[log]
	decorate = true

[pull]
	rebase = true

[sendemail "..."]
    ...

[user]
	email = "..."
	name = "..."
	signingKey = "..."
```

# Game version and error details

E.g. creating a commit in "Your first commit" fails with output:
```
$ git add .; git commit
error: gpg failed to sign the data
fatal: failed to write commit object
```

using the version from itch.io (`--version` outputs `3.2.3.stable.official`)

# Workaround
I could get everything to work by running the program with `XDG_CONFIG_HOME=/dev/null`.
Apparently (at least my current version+config of) git prefers `$XDG_CONFIG_HOME/git/config` over `$HOME/.gitconfig` (which is set by the game as far as I can tell)
