### ISSUE TITLE
FTBTS on Ubuntu 20.04

### ISSUE THREAD

**Issue by BenBE** [git-learning-game/git-hydra#4]
Trying to build the source on Lubuntu 20.04 I run into several build issues.

First of, it would be nice if the README or some build instruction file would detail the required dependencies for building. Going by the inevitable error messages when these failed, I noticed, this list should contain at least: godot, wget, zip (on Linux) and 7z (on Windows).

With this out of the way, there's unfortunately no package on Ubuntu 20.04 providing `/usr/bin/godot`but only `/usr/bin/godot3`. Thus modifying the `Makefile` accordingly you run into yet another build issue straight away:

```
$ make
mkdir -p build/"git-hydra"-linux
\godot3 --export "Linux" "build/"git-hydra"-linux/"git-hydra""
Godot Engine v3.2.stable.custom_build - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
 
reimport: begin: Importiere Nutzerinhalte erneut steps: 31
        reimport: step 0: typewriter_ding.wav
        reimport: step 1: swoosh.wav
        reimport: step 2: swish.wav
        reimport: step 3: success.wav
        reimport: step 4: poof.wav
        reimport: step 5: buzzer.wav
        reimport: step 6: tree.svg
        reimport: step 7: ref.svg
        reimport: step 8: pop.wav
        reimport: step 9: head.svg
        reimport: step 10: document.svg
        reimport: step 11: commit.svg
        reimport: step 12: blob.svg
        reimport: step 13: untracked.svg
        reimport: step 14: removed.svg
        reimport: step 15: new.svg
        reimport: step 16: modified.svg
        reimport: step 17: conflict.svg
        reimport: step 18: reset-hard.svg
        reimport: step 19: rebase.svg
        reimport: step 20: rebase-interactive.svg
        reimport: step 21: push.svg
        reimport: step 22: pull.svg
        reimport: step 23: merge.svg
        reimport: step 24: init.svg
        reimport: step 25: commit-auto.svg
        reimport: step 26: cherry-pick.svg
        reimport: step 27: checkout.svg
        reimport: step 28: bisect-start.svg
        reimport: step 29: bisect-good.svg
        reimport: step 30: bisect-bad.svg
ERROR: _fs_changed: Cannot export project with preset 'Linux' due to configuration errors:
Keine Exportvorlagen am erwarteten Pfad gefunden:
/home/user/.local/share/godot/templates/3.2.stable/linux_x11_64_debug
Keine Exportvorlagen am erwarteten Pfad gefunden:
/home/user/.local/share/godot/templates/3.2.stable/linux_x11_64_release

   At: editor/editor_node.cpp:611.
ERROR: _fs_changed: Project export failed for preset 'Linux', the export template appears to be missing.
   At: editor/editor_node.cpp:634.
reimport: end
make: *** [Makefile:7: linux] Fehler 1
```

Apart from this, it'd be great, if the internal calls in the build process respected `LC_ALL`, thus error traces without l10n could easily be created.

**Comment by blinry** [comment]
Good point – we should document how to build your own binaries! Thanks for reporting all of that! :)

As a quick workaround, just in case you're not aware of that: for development, you don't need to build your own binaries. You should be able to run the game using `godot3 scenes/main.tscn` – does that work for you?

You can also open the game in the Godot editor with `godot3 project.godot`, and run it from there using F5.

**Comment by blinry** [comment]
(What does FTBTS mean?)

**Comment by BenBE** [comment]
FTBTS (Fails To Build From Source) is commonly used when packaging software, meaning that the provided sources require further modification or are missing something in order to build them.

**Comment by BenBE** [comment]
> You should be able to run the game using `godot3 scenes/main.tscn` – does that work for you?

Yes. works. Might be worth a quick note in the readme.
Opening in the editor works fine too.

**Comment by blinry** [comment]
Again, thanks for reporting these issues, @BenBE! <3
